### ISSUE TITLE
Implement V1 endpoints

### ISSUE THREAD

**Issue by emostov** [paritytech/substrate-api-sidecar#227]
## Initial v1.0

- [x] /accounts/{accountId}/balance-info (conversion of existing endpoint)  (#248)
- [x] /accounts/{accountId}/staking-info (conversion of existing endpoint)  (#248)
- [x] /accounts/{accountId}/staking-payouts (#217)
- [x] /accounts/{accountId}/vesting-info (conversion of existing endpoint)  (#248)
- [x] /blocks/{blockId} (conversion of existing endpoint)
- [x] /blocks/head (conversion of existing endpoint)
- [x] /node/network (#226)
- [x] /node/transaction-pool (#226)
- [x] /node/version (#226)
- [x] /transaction (conversion of existing endpoint)  (#246)
- [x] /transaction/dry-run (#236)
- [x] /transaction/fee-estimate (conversion of existing endpoint)  (#246)
- [x] /transaction/material (conversion of existing endpoint) (#246)
- [x] /runtime/code (https://github.com/paritytech/substrate-api-sidecar/pull/228)
- [x] /runtime/spec (https://github.com/paritytech/substrate-api-sidecar/pull/228)
- [x] /runtime/metadata (conversion of existing endpoint) (#242)
- [x] /pallets/staking/progress (conversion of existing endpoint) (#248)
- [x] /pallets/{palletId}/storage/{storageItemId}

### Other
- [x] hosted swagger ui (#239)
