### ISSUE TITLE
[Tracking] Sidecar Future Release Roadmap

### ISSUE THREAD

**Issue by TarikGul** [paritytech/substrate-api-sidecar#697]
Below are current issues, features, or optimizations that will be covered for sidecars future releases. 

- [x] Create a `api.at` wrapper to work as a historicApi. Remove all `.at` calls, and refactor. [polkadot/api #4023](https://github.com/polkadot-js/api/pull/4023/files#diff-c398231e64805214d508b419463b7443e3d7dfdc5bed4a1f425be1d43f03026eR61)
  - This should be co-written with a PR that will bump up the deps past `@polkadot/api@6.2.1` stable
- [X] [Breaking Change] Pallets-Storage V14 update. [substrate-api-sidecar #710]
- [X] [Breaking Change] Vesting-info response [substrate-api-sidecar #717]
- [X] Benchmarking [substrate-api-sidecar #693](https://github.com/paritytech/substrate-api-sidecar/issues/693)
- [X] Bump `@polkadot/api` to the next stable version above v6.2.1.
