### ISSUE TITLE
[ROADMAP] Substrate-api-sidecar roadmap for 2022

### ISSUE THREAD

**Issue by TarikGul** [paritytech/substrate-api-sidecar#870]
## 2022 Roadmap

**Summary**: This list will contain a lot of our focuses for the coming year, and the main features and reworks we will be implementing. Feedback, and suggestions are absolutely welcome. That being said, this list is capable of growing, and we hope to get more feature requests as time goes on.

### Features:  

- [ ] XCM message parsing per block. This will give users the ability to attach a query param such as `?xcm=true` and the current block request will return all the parsable messages. via https://github.com/paritytech/substrate-api-sidecar/issues/732 (In Progress)
- [x] Contracts support for !ink. Currently we are only going to implement getting account-info and balance-info. As the base foundation is built out, we can add more functionality that is deemed necessary. via https://github.com/paritytech/substrate-api-sidecar/issues/795
- [x] Support for StorageNMaps in `/pallets/*`. via https://github.com/paritytech/substrate-api-sidecar/issues/811
- [ ] Expansion of the pallets endpoints to broaden its scope. via https://github.com/paritytech/substrate-api-sidecar/issues/293
- [ ] Paginated storage queries. via https://github.com/paritytech/substrate-api-sidecar/issues/562
- [x] Tx Fee from on chain events. via https://github.com/paritytech/substrate-api-sidecar/issues/756
- [ ] Tokens-Info endpoint similar to balance-info
- [ ] Multiple endpoints fallback for ws connection. via https://github.com/paritytech/substrate-api-sidecar/issues/649
- [ ] Support for parachains-staking via https://github.com/paritytech/substrate-api-sidecar/issues/886
- [x] Add query parameter support for denominating an atomic balance to its human readable value. via https://github.com/paritytech/substrate-api-sidecar/pull/914
- [X] Replace `@substrate/calc` with `payment::queryInfo` via https://github.com/paritytech/substrate-api-sidecar/pull/937
- [X] Add `includeFee` query param to `/node/transaction-pool`. Computes a extrinsics priority in the pool, and attaches the fields `tip`, `partialFee`, and `priority` via https://github.com/paritytech/substrate-api-sidecar/pull/931
- [X] Add `/blocks` ednpoint which enforces a `range` query param to support querying multiple blocks at once via https://github.com/paritytech/substrate-api-sidecar/pull/954

### Testing and Infrastructure
- [ ] Completely full coverage for e2e-endpoints. via https://github.com/paritytech/substrate-api-sidecar/issues/645
- [ ] Currently benchmarking only targets `/blocks`, the foundation is all set to expand the benchmarking to all other endpoints. 
- [ ] Add automation/auditing around test coverage.
- [ ] Expand our documentation when it comes to potential upstream errors from substrate and polkadot-js. 
- [X] Automate updating polkadot-js dependencies and resolutions via https://github.com/paritytech/substrate-api-sidecar/pull/904 and https://github.com/paritytech/substrate-js-dev/pull/63

### Reworks

As the ecosystem grows, and parachains become a larger focus for tooling, and extensibility our goal in sidecar is to make it easier to support various pallets, and specifications that might be specific to a substrate-based chain. Our rework of sidecar will focus on the following, but is not limited to:

- [ ] Create a PnP model that will allow users to build controllers, and share them within the community. 
    - [ ] Focus on creating a wrapper api around polkadot-js which will be exposed to users, that will focus on parachain support.
- [ ] Separate sidecars core logic into separate packages that will allow exchanges and external chains to easily configure and build their own sidecar servers.

**Comment by TarikGul** [comment]
Would be good to consider adding https://github.com/paritytech/substrate-api-sidecar/issues/1011 to the Roadmap for transaction construction.

**Comment by TarikGul** [comment]
Closing as it's 2023, and a new roadmap will be released.
